export const defaultConfig = {
  windowBackground: '#4c4c4c',
  userCdEnabled: true,
  userCdMinute: 15,
  listLimitEnabled: true,
  listLimitCount: 10,
  guardPowerEnabled: true,
  guardPowerTimesInfinity: false,
  guardPowerPerWeek: 2,
  appMainFont: '',
  songNumberEnabled: true,
  songNumberColor: '#ffffff',
  songNumberBold: false,
  songNumberShadow: false,
  songNameColor: '#efe47a',
  songNameBold: false,
  songNameShadow: true,
  userNameColor: '#ffffff',
  userNameBold: false,
  userNameShadow: true,
  bullyingSongsRaw: ''
}